Spring Boot 可以轻松创建Spring驱动的生产级应用程序和服务。

== 特性 ==
* 快速入门
* 开箱即用
* 强大的整合能力(如: embedded servers, security, metrics, health checks, externalized configuration)
* 零配置
* 提供了一个运行spring脚本的命令行工具

== 入门 ==
https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/pdf/spring-boot-reference.pdf

== 示例 ==
[source,java,indent=0]
----
	import org.springframework.boot.*;
	import org.springframework.boot.autoconfigure.*;
	import org.springframework.web.bind.annotation.*;

	@RestController
	@SpringBootApplication
	public class Example {

		@RequestMapping("/")
		String home() {
			return "Hello World!";
		}

		public static void main(String[] args) throws Exception {
			SpringApplication.run(Example.class, args);
		}

	}
----



== 帮助 ==
* 参考手册
* Spring 基础
  https://spring.io/guides[guides].
* 升级问题
  https://github.com/spring-projects/spring-boot/wiki
* 其他问题
  https://stackoverflow.com/tags/spring-boot
  https://gitter.im/spring-projects/spring-boot
* Bug提交
  https://github.com/spring-projects/spring-boot/issues



== BUG提交流程
Spring Boot uses GitHub's integrated issue tracking system to record bugs and feature
requests. If you want to raise an issue, please follow the recommendations below:

* 先确认BUG是否已经提交?
  https://github.com/spring-projects/spring-boot/search?type=Issues
* 提交BUG
  https://github.com/spring-projects/spring-boot/issues/new[create a new issue].
* 提交BUG包含版本, BUG详细说明等.
* 使用Markdown +++```+++ 转义异常信息.
* 提交BUG测试用例.



== 构建
	JDK 1.8+
	Maven版本 v3.5+
	MAVEN_OPTS =-Xmx512m

	mvn clean install

=== 构建参考手册

先构建工程spring-boot:

[indent=0]
----
	$ ./mvnw clean install
----

然后构建插件spring-boot-maven-plugin:

[indent=0]
----
	$ ./mvnw clean install -pl spring-boot-project/spring-boot-tools/spring-boot-maven-plugin -Pdefault,full
----

然后构建插件spring-boot-starters:

[indent=0]
----
	$ ./mvnw clean install -f spring-boot-project/spring-boot-starters
----

最后执行文档构建:

[indent=0]
----
	$ ./mvnw clean prepare-package -pl spring-boot-project/spring-boot-docs -Pdefault,full
----

文档生成目录: `spring-boot-project/spring-boot-docs/target/contents/reference`


== 模板 ==
=== spring-boot
* `SpringApplication`, 编写单机应用. 刷新 Spring `ApplicationContext`
* 嵌入式服务器(Tomcat, Jetty or Undertow)
* 外部化配置支持
* 方便的`ApplicationContext`初始化，包括支持合理的日志记录

=== spring-boot-autoconfigure
基于classpath的自动配置. `@EnableAutoConfiguration` 触发Spring自动配置.
包存在即配置.

=== spring-boot-starters
Starters 描述JAR包依赖关系. 一站式依赖自动管理.

=== spring-boot-cli
命令行工具, 快速编写应用. Spring CLI
监控文件, 自动按需重新编译与重启.

=== spring-boot-actuator
Actuator endpoints 应用性能监控.
`HealthEndpoint`, `EnvironmentEndpoint`, `BeansEndpoints`.

=== spring-boot-actuator-autoconfigure
Starters 描述JAR包依赖关系. 一站式依赖自动管理.

=== spring-boot-test
测试支持

=== spring-boot-test-autoconfigure

=== spring-boot-loader
java -jar

=== spring-boot-devtools
热交换/热部署

== 样例
Groovy 样例:
spring-boot-project/spring-boot-cli/samples[spring-boot-cli/samples]. 
`spring run <sample>.groovy` 

link:spring-boot-samples[spring-boot-samples]
be built with maven and run by invoking `java -jar target/<sample>.jar`.



== 指导手册
https://spring.io/:

* https://spring.io/guides/gs/spring-boot/
* https://spring.io/guides/gs/actuator-service/
* https://spring.io/guides/gs/convert-jar-to-war/ 如何部署WAR?

== 执照
Apache 2.0 license

